- hosts: "{{apb_host}}"
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
  tasks:
    - name: running shell
      shell:
        cmd: "{{apb_shell | expanduser}}"
      register: apb_shell_output
      retries: 5
      until: apb_shell_output.rc == 0
      delay: 1
      when: apb_runtype == "shell"

    - debug:
        msg:
          - name:{{ansible_env.u_name | default("")}}
          - describe:{{ansible_env.u_describe | default("")}}
          - stdout:{{ apb_shell_output.stdout }}
          - stderr:{{ apb_shell_output.stderr }}
      when: apb_runtype == "shell"

    - name: running script
      ansible.builtin.script: "{{apb_script | expanduser}}"
      register: apb_script_output
      retries: 5
      until: apb_script_output.rc == 0
      delay: 1
      when: apb_runtype == "script"

    - debug:
        msg:
          - name:{{ansible_env.u_name | default("")}}
          - describe:{{ansible_env.u_describe | default("")}}
          - stdout:{{ apb_script_output.stdout }}
          - stderr:{{ apb_script_output.stderr }}
      when: apb_runtype == "script"
